#!/usr/bin/env python3
"""Generate rules/builtin/rules.yml from analyzer source and classify_rule mapping.

Usage:
    python scripts/generate_rules_yml.py

This is a one-time generation script. After generation, the YAML file is the
source of truth for rule metadata. Re-run when adding new rules.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "scripts"
RULES_DIR = ROOT / "rules" / "builtin"

# Regex patterns matching the analyzer emission conventions
AST_ADD_RE = re.compile(
    r'\b(?:Add|CheckPascalCase)\(\s*(?:\w+\.\w+,\s*)?'
    r'"(?P<id>LEGACY_[A-Za-z0-9_]+)"'
)
SEM_ADD_RE = re.compile(
    r'\bAdd\(\s*diagnostics,\s*[^,]+,\s*[^,]+,\s*"(?P<id>(?:SEM|EF|ASP|P|RCS)\d{2,4})"'
)


def get_rule_ids() -> dict[str, list[str]]:
    """Extract rule IDs from analyzers using Python regex."""
    result = {}
    for name, path, pattern in [
        ("ast", SCRIPTS / "csharp-ast-analyzer" / "Program.cs", AST_ADD_RE),
        ("semantic", SCRIPTS / "csharp-semantic-analyzer" / "Program.cs", SEM_ADD_RE),
    ]:
        if not path.exists():
            result[name] = []
            continue
        text = path.read_text(encoding="utf-8")
        ids = sorted(set(m.group("id") for m in pattern.finditer(text)))
        result[name] = ids
    return result


def classify_rule(rule_code: str) -> str:
    """Mirror of review/analyzer/triage.py classify_rule."""
    if rule_code.startswith("SEM"):
        return "semantic"
    if rule_code.startswith("EF"):
        return "reliability"
    if rule_code.startswith("ARCH") or rule_code.startswith("LAYER"):
        return "architecture"
    if rule_code.startswith("ASYNC"):
        return "best-practice"
    if rule_code.startswith("LEGACY_SEC") or rule_code.startswith("SEC"):
        return "security"
    if rule_code.startswith("LEGACY_BP") or rule_code.startswith("BP"):
        return "best-practice"
    if rule_code.startswith("LEGACY_CC") or rule_code.startswith("CC"):
        return "complexity"
    if rule_code.startswith("LEGACY_P") or rule_code.startswith("P"):
        return "performance"
    if rule_code.startswith("LEGACY_S") or rule_code.startswith("S"):
        return "style"
    if rule_code.startswith("DUP"):
        return "best-practice"
    if rule_code.startswith("CS"):
        return "reliability"
    if rule_code.startswith("CA"):
        return "best-practice"
    if rule_code.startswith("IDE"):
        return "style"
    return "best-practice"


def main():
    RULES_DIR.mkdir(parents=True, exist_ok=True)
    ids = get_rule_ids()
    all_rules = ids.get("ast", []) + ids.get("semantic", [])

    lines = ["# Auto-generated rules catalog", "# Generated by: generate_rules_yml.py", "#", f"# Total rules: {len(all_rules)}", f"# AST: {len(ids.get('ast', []))}", f"# Semantic: {len(ids.get('semantic', []))}", "", "rules:"]
    for rid in sorted(all_rules):
        cat = classify_rule(rid)
        lines.append(f'  - id: "{rid}"')
        lines.append(f"    category: {cat}")
        lines.append("")

    content = "\n".join(lines)
    out = RULES_DIR / "rules.yml"
    out.write_text(content, encoding="utf-8")
    print(f"Generated: {out} ({len(all_rules)} rules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())