"""Render and optionally publish review findings as PR comments."""
from __future__ import annotations

import json
import os
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


def _body(issue: dict) -> str:
    mapping = ""
    if issue.get("cwe") or issue.get("owasp"):
        mapping = f"\n\nSecurity mapping: {issue.get('cwe', '')} {issue.get('owasp', '')}".rstrip()
    suggestion = issue.get("suggestion") or ""
    return (
        f"**[{issue.get('severity', 'info').upper()}] {issue.get('rule', 'UNKNOWN')}**\n\n"
        f"{issue.get('message', '')}{mapping}\n\n"
        f"{suggestion}\n\n"
        "_Generated by dotnet-code-review._"
    )


def render_github_comments(report: dict) -> list[dict]:
    """Create GitHub Reviews API comment payloads."""
    comments = []
    for issue in report.get("issues", []) or []:
        path = issue.get("file") or ""
        line = int(issue.get("line") or 1)
        if not path or line <= 0:
            continue
        comments.append({
            "path": path.replace("\\", "/"),
            "line": line,
            "side": "RIGHT",
            "body": _body(issue),
        })
    return comments


def render_azure_comments(report: dict) -> list[dict]:
    """Create Azure DevOps pull-request thread payloads."""
    comments = []
    for issue in report.get("issues", []) or []:
        path = issue.get("file") or ""
        line = int(issue.get("line") or 1)
        if not path or line <= 0:
            continue
        comments.append({
            "comments": [{"parentCommentId": 0, "content": _body(issue), "commentType": 1}],
            "status": 1,
            "threadContext": {
                "filePath": "/" + path.replace("\\", "/").lstrip("/"),
                "rightFileStart": {"line": line, "offset": 1},
                "rightFileEnd": {"line": line, "offset": 1},
            },
        })
    return comments


def render_pr_comments(report: dict, provider: str) -> list[dict]:
    if provider == "github":
        return render_github_comments(report)
    if provider in {"azure", "azure-devops"}:
        return render_azure_comments(report)
    raise ValueError(f"Unsupported PR provider: {provider}")


def write_pr_comments(report: dict, provider: str, output_path: str) -> int:
    payload = render_pr_comments(report, provider)
    Path(output_path).write_text(
        json.dumps({"provider": provider, "comments": payload}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return len(payload)


def _post_json(url: str, token: str, payload: dict) -> dict:
    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=20) as response:
        raw = response.read().decode("utf-8", errors="replace")
    return json.loads(raw) if raw else {}


def publish_pr_comments(report: dict, provider: str, **kwargs) -> dict:
    """Publish comments only when explicitly requested by the CLI."""
    comments = render_pr_comments(report, provider)
    if provider == "github":
        token = kwargs.get("token") or os.environ.get("GITHUB_TOKEN")
        repo = kwargs.get("repo") or os.environ.get("GITHUB_REPOSITORY")
        number = kwargs.get("number") or os.environ.get("GITHUB_PR_NUMBER")
        sha = kwargs.get("sha") or os.environ.get("GITHUB_SHA")
        if not token or not repo or not number or not sha:
            raise ValueError("GitHub publishing requires GITHUB_TOKEN, GITHUB_REPOSITORY, GITHUB_PR_NUMBER and GITHUB_SHA")
        url = f"https://api.github.com/repos/{repo}/pulls/{number}/reviews"
        result = _post_json(url, token, {"commit_id": sha, "body": "dotnet-code-review findings", "event": "COMMENT", "comments": comments})
        return {"provider": provider, "published": len(comments), "response": result}

    token = kwargs.get("token") or os.environ.get("SYSTEM_ACCESSTOKEN")
    organization = kwargs.get("organization") or os.environ.get("SYSTEM_COLLECTIONURI", "").rstrip("/")
    project = kwargs.get("project") or os.environ.get("SYSTEM_TEAMPROJECT")
    repository = kwargs.get("repo") or os.environ.get("BUILD_REPOSITORY_ID")
    number = kwargs.get("number") or os.environ.get("SYSTEM_PULLREQUEST_PULLREQUESTNUMBER")
    if not token or not organization or not project or not repository or not number:
        raise ValueError("Azure publishing requires SYSTEM_ACCESSTOKEN, SYSTEM_COLLECTIONURI, SYSTEM_TEAMPROJECT, BUILD_REPOSITORY_ID and SYSTEM_PULLREQUEST_PULLREQUESTNUMBER")
    base = f"{organization}/{urllib.parse.quote(project, safe='')}/_apis/git/repositories/{repository}/pullRequests/{number}/threads?api-version=7.1"
    posted = 0
    for thread in comments:
        request = urllib.request.Request(
            base,
            data=json.dumps(thread).encode("utf-8"),
            headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(request, timeout=20):
            posted += 1
    return {"provider": "azure", "published": posted}
